### PR TITLE
Landing page

### LINKED ISSUE #66: Design landing page
- Add a call to action
- Info on Yamovie

4-6 hours of work

### PR DESCRIPTION
**Pull request by afterafx**
Closes #66

### CODE REVIEW

**Comment by glenflorendo** [comment]
@afterafx I don't see your new commits

**Comment by glenflorendo** [comment]
Ready to merge.

**Comment by samsaksfithian** [comment]
Also closes #74

**Comment by samsaksfithian** [comment]
Also closes #63

**Pull request merged**
